# Generated by Django 6.0.7 on 2026-08-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('general', 'General question'), ('private', 'Private session or corporate workshop'), ('sponsorship', 'Sponsorship')], default='general', max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntensiveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('instagram_or_website', models.CharField(blank=True, max_length=200)),
                ('about_yourself', models.TextField()),
                ('prior_experience', models.TextField()),
                ('why_framing', models.TextField()),
                ('goals', models.TextField()),
                ('accommodations', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('payment_plan_needed', models.BooleanField(default=False, verbose_name='Will you need a payment plan?')),
                ('payment_plan_choice', models.CharField(blank=True, choices=[('option_a', 'Option A — $550 / $1,000 / $1,050 (total $2,550)'), ('option_b', 'Option B — $500 / $700 / $700 / $650 (total $2,550)')], max_length=20)),
                ('sponsored_seat_consideration', models.BooleanField(default=False, verbose_name='Would you like to be considered for the sponsored seat?')),
                ('sponsored_seat_statement', models.TextField(blank=True)),
                ('attendance_commitment', models.TextField(blank=True)),
                ('interview_availability', models.TextField(verbose_name='What days and times work best for a 10-minute call?')),
                ('interview_format', models.CharField(choices=[('video', 'Video'), ('phone', 'Phone')], max_length=10)),
                ('application_fee_status', models.CharField(choices=[('paid', "Yes, I've submitted the fee"), ('no', 'No, not yet'), ('waiver', 'I have requested a fee waiver')], max_length=10)),
                ('liability_consent', models.BooleanField(default=False, verbose_name='I understand the liability waiver requirement and am ready to sign')),
            ],
            options={
                'verbose_name_plural': 'intensive applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentalValueApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('object_description', models.TextField(verbose_name='What is the object?')),
                ('why_it_matters', models.TextField(verbose_name='Why does it matter to you?')),
                ('origin', models.TextField(verbose_name='Who does it belong to or where did it come from?')),
                ('photo', models.ImageField(blank=True, upload_to='sentimental/', verbose_name='Photo of the object')),
            ],
            options={
                'verbose_name_plural': 'sentimental value applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(choices=[('new_york', 'New York'), ('new_jersey', 'New Jersey'), ('philadelphia', 'Philadelphia'), ('seattle', 'Seattle'), ('albuquerque', 'Albuquerque'), ('santa_fe', 'Santa Fe'), ('other', 'Other')], max_length=40)),
            ],
            options={
                'verbose_name_plural': 'weekend interest entries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
