# Generated by Django 6.0.8 on 2026-09-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intensiveapplication",
            name="payment_plan_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("option_a", "Option A — deposit, then two further payments"),
                    ("option_b", "Option B — deposit, then three further payments"),
                ],
                max_length=20,
            ),
        ),
    ]
